### PR TITLE
fix add_offense positional args deprecation

### LINKED ISSUE #1: deprecation warning on latest rubocop
```
/Users/bgentry/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-sequel-0.0.1/lib/rubocop/cop/sequel/save_changes.rb:13
Warning: The usage of positional location, message, and severity
parameters to Cop#add_offense is deprecated.
Please use keyword arguments instead.

The positional arguments version of Cop#add_offense will be removed in
RuboCop 0.52
```

### PR DESCRIPTION
**Pull request by bgentry**
Fixes #1.

### CODE REVIEW

**Comment by cyberdelia** [comment]
@bgentry It might requires to bump the version in the gemspec too.

Also hi  👋

**Comment by bgentry** [comment]
@cyberdelia added a version bump as well. Cheers✌️

**Comment by bgentry** [comment]
hmm apparently this is totally busted now, will work on it

**Comment by cyberdelia** [comment]
I removed the useless ``Gemfile.lock`` on master, so you might have to rebase too.

**Comment by bgentry** [comment]
so I fixed the specs and then ran rubocop locally to discover that there were a bunch of complaints. Not sure which were new to the version bump and which were pre-existing, but I did my best to fix all of them. Only this one remains which seems ridiculous to me:

```
➜  rubocop-sequel git:(master) ✗  rubocop -a
Inspecting 13 files
..........C..

Offenses:

spec/rubocop/cop/sequel/migration_name_spec.rb:3:1: C: Block has too many lines. [30/25]
describe RuboCop::Cop::Sequel::MigrationName, :config do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

13 files inspected, 1 offense detected
```

It's complaining about the length of the rspec block??

**Comment by bgentry** [comment]
also it wants rubocop-sequel.rb to be renamed to use snake case but I didn't think it was appropriate for me to do that.

**Comment by cyberdelia** [comment]
@bgentry Open another issue maybe?

**Pull request merged**
